apiVersion: apps/v1                       
kind: Deployment                          
metadata:                                 
  namespace: gabriel                      
  name: goserver               
  labels:                                 
    app: goserver              
spec:                                     
  replicas: 2                             
  selector:                               
    matchLabels:                          
      app: goserver                  
  template:                               
    metadata:                 
      labels:                 
        app: goserver  
    spec:                     
      containers:             
        - name: goserver      
          image: "gabrielrodriguesdev/hello-go:0.0.9"
          livenessProbe:                                                  #Definindo teste de vivência.
            initialDelaySeconds: 2                                        #Definindo para só iniciar os testes, após 2 segundos (para dar tempo do container finalizar a criação etc)
            httpGet:                                                      #Definindo protocolo de requisição HTTP
              path: /helthz                                               #Definindo path do endpoint
              port: 8000                                                  #Definindo a porta do container
            periodSeconds: 5                                              #Definindo o tempo em segundos, no qual ele irá refazer esse teste
            failuredThreshold: 1                                          #Definindo qual será a quantidade de erros minimas para que seja reiniciado o container.
            timeout: 1                                                    #Definindo tempo de espera para uma resposta de uma requisição | Exemplo -> Se a aplicação me responder 200 em até 10 segundos eu aceito, mas se passar disso já identifico como erro.
            sucessThreshold: 3                                            #Definindo quantidade de testes que será feito com base no periodo do timeout | Exemplo -> Nesse exemplo ele vai realizar 3 (sucessThreshold) testes a cada 1 segundo (timeout), caso receba retorno de sucesso nesses 3 testes ele entende que está tudo certo.
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          envFrom:                                                  
            - secretRef:                                            
                name: goserver-secret                               
---
apiVersion: v1
kind: Service
metadata:
  namespace: gabriel
  name: goserver-service
spec:
  selector: 
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 80
      targetPort: 80
      protocol: TCP