apiVersion: apps/v1                       #Versão
kind: Deployment                          #Tipo do objeto
metadata:                                 #Propriedades do objeto (Nesse contexto é o Deployment)
  namespace: gabriel                      #Configurando deployment no namespace gabriel (que foi previamente criado)
  name: goserver-deployment               #Nome do objeto
  labels:                                 #Labels -> São rotulos, uma espécie de alías são compostos por "key:value"
    app: goserver-deployment              #Key/Value -> Uma label 
spec:                                     #Especificações do nosso objeto
  replicas: 2                             #Definindo que queremos 2 réplicas de uma pod sempre no ar (Vamos definir como vai ser esses pods em "template").
  selector:                               #Seletor e ele consegue buscar pelos seletores definidos (labels)
    matchLabels:                          #
      app: goserver-pod                   #Labels Key:Value
  template:                               # Template do pod que será replicado 2 vezes pelo replicaSet -> O que significa que 2 pods conforme as informções descritas a baixo sempre vai estar em execução.
    metadata:                 
      labels:                 
        app: goserver-pod  
    spec:                     
      containers:             
        - name: goserver      
          image: "gabrielrodriguesdev/hello-go:0.0.2" 