apiVersion: apps/v1                       
kind: Deployment                          
metadata:                                 
  namespace: gabriel                      
  name: goserver               
  labels:                                 
    app: goserver              
spec:                                     
  replicas: 2                             
  selector:                               
    matchLabels:                          
      app: goserver                  
  template:                               
    metadata:                 
      labels:                 
        app: goserver  
    spec:                     
      containers:             
        - name: goserver      
          image: "gabrielrodriguesdev/hello-go:0.0.9" 
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          envFrom:                                                  #Definindo que as variavéis de ambiente virão de uma fonte externa
            - secretRef:                                            #Lendo as informações a partir de um secret
                name: goserver-secret                               #Selecionando o secret goserver-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: gabriel
  name: goserver-service
spec:
  selector: 
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 80
      targetPort: 80
      protocol: TCP