apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gabriel
  name: goserver-hpa
spec:                                                     #Especificação do objeto que será monitorado para escalonamento
  scaleTargetRef:                                         #Objeto alvo que será observado para ser escalonado caso necessário
    apiVersion: apps/v1                                   #Versão do objeto a ser escalonado
    kind: Deployment                                      #Tipo do objeto que será escaloado
    name: goserver                                        #Nome do objeto que será escalonado
  minReplicas: 1                                          #Minimo de replica que necesitam estar em execução (Nunca devemos trabalhar com 1 replica apenas, no minimo duas)
  maxReplicas: 4                                          #Maximo de replicas -> Só irá escalar até 3 máquinas
  targetCPUUtilizationPercentage: 30                      #A partir dos 30% de uso total da CPU, cluster começará a escalar os pods.
